language: node_js
  - "10"

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle@5.0.0
  - npm install

script:
  - ganache-cli -m "recipe program twist race bind host dutch fog item rigid decline media" &
  - sleep 5
  - truffle test